---

dist: focal

language: python
python:
  - "3.8"
addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main'
        key_url: 'https://apt.releases.hashicorp.com/gpg'
    update: true
    packages:
      - bridge-utils
      - dnsmasq-base
      - ebtables
      - libvirt-bin
      - libvirt-dev
      - qemu-kvm
      - qemu-utils
      - ruby-dev
      - ca-certificates
      - curl
      - gcc
      - iproute2
      - sudo
      - vagrant

install:
#  - wget https://releases.hashicorp.com/vagrant/$VAGRANT_VER/vagrant_"$VAGRANT_VER"_x86_64.deb
#  - sudo apt -y install ./vagrant_"$VAGRANT_VER"_x86_64.deb
  - vagrant plugin install vagrant-libvirt
  - pip install wheel pyopenssl tox
  - sudo chmod o+rwx /var/run/libvirt/libvirt-sock
  - ./configure

script:
  - mv ../ansible-role-libvirt-host ../tcharl.ansible_role_libvirt_host
  - travis_wait 30 tox -e test-exec -- --scenario-name kvm
branches:
  only:
    - master
