---
- include: prelude.yml
- include: validate.yml
- include: install-daemon.yml
  when: libvirt_host_install_daemon | bool
- include: install-client.yml
  when:
    - not libvirt_host_install_daemon | bool
    - libvirt_host_install_client | bool
- name: Run post-install stage
  include: "{{ post_install_path }}"
  with_first_found:
    - files:
        - post-install-{{ ansible_distribution }}.yml
        - post-install-{{ ansible_os_family }}.yml
      skip: true
  loop_control:
    loop_var: post_install_path
- include: config.yml
  when: libvirt_host_install_daemon | bool
- include: pools.yml
- include: networks.yml
