---
- name: Include lvm role to create VG
  include_role:
    name: tcharl.ansible_manage_lvm
  when: >
    manage_lvm is defined and
    manage_lvm and
    libvirt_host_pools |  map(attribute='type') | select('match', '^lvm2$') | join(',') | length > 0

- name: Ensure libvirt dir storage pool directories exist
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode|int(base=8) }}"
    state: directory
  when: item.type == "dir"
  loop: "{{ libvirt_host_pools | flatten(levels=1) }}"
  become: True

- name: Ensure libvirt LVM storage pool directories exist
  lvg:
    vg: "{{ item.source }}"
    pvs: "{{ item.pvs }}"
  when: item.type in ["lvm2", "logical"]
  loop: "{{ libvirt_host_pools | flatten(levels=1) }}"
  become: True

- include: rbd.yml
  when: item.type == "rbd"
  loop: "{{ libvirt_host_pools | flatten(levels=1) }}"
  become: True

- name: Ensure libvirt storage pools are defined
  virt_pool:
    name: "{{ item.name }}"
    command: define
    xml: "{{ item.xml | default(lookup('template', 'pool.xml.j2')) }}"
    uri: "{{ libvirt_host_uri | default(omit, true) }}"
  loop: "{{ libvirt_host_pools | flatten(levels=1) }}"
  become: True

- name: Ensure libvirt storage pools are active
  virt_pool:
    name: "{{ item.name }}"
    state: active
    uri: "{{ libvirt_host_uri | default(omit, true) }}"
  loop: "{{ libvirt_host_pools | flatten(levels=1) }}"
  become: True

- name: Ensure libvirt storage pools are started on boot
  virt_pool:
    name: "{{ item.name }}"
    autostart: yes
    uri: "{{ libvirt_host_uri | default(omit, true) }}"
  loop: "{{ libvirt_host_pools | flatten(levels=1) }}"
  become: True
